---
- name: Install yum-utils
  yum:
    name: yum-utils

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data

- name: Install lvm2
  yum:
    name: lvm2

- name: docker repository
  yum_repository:
    name: docker-ce-stable
    description: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker-ce
  yum:
    name: docker-ce-18.06.1.ce
    update_cache: true

- name: Activate docker-ce
  systemd:
    state: started
    name: docker

- name: Verify docker is installed
  shell: "docker run hello-world"